version: "3.6"
services:
  nginx:
    image: nginx
    build: ./nginx/
    container_name: nginx
    volumes:
#      - "/home/rey/docker/nginx/django.conf:/etc/nginx/conf.d/django.conf:pro"
#      - "/etc/nginx/nginx.conf.default:/etc/nginx/nginx.conf.default:pro"
#      - "/etc/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:pro"
#      - "./static:/usr/share/nginx/html/static:pro"
#      - "./static:/djangoProject/static:pro"
      - "./static:/usr/share/nginx/html/static:pro"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:pro"
      - "./nginx/django.conf:/etc/nginx/conf.d/django.conf:pro"
      - "./log:/var/log/nginx:rw"
    ports:
      - "10080:80"
      - "10443:443"
    privileged: true
    expose:
      - "10080"
    restart: always

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "13306:3306"
    restart: always
    command: --default-authentication-plugin=mysql_native_password --mysqlx=0
    environment:
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - "/home/rey/mysql:/var/lib/mysql:rw"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: web
    container_name: web
    restart: always
    depends_on:
      - mysql
      - nginx
    ports:
      - "12000:12000"
    stdin_open: true
    tty: true

networks:
  default:
    driver: bridge
